### ISSUE TITLE
How to use color

### ISSUE THREAD

**Issue by giacomodabisias** [jrgnicho/realsense_drivers#1]
Hi,
I am directly using the API provided by DSAPI.h
I printed the supported format list 

```
0 : width 628 height 468 fps 90 pixel format 0
1 : width 628 height 468 fps 60 pixel format 0
2 : width 628 height 468 fps 30 pixel format 0
3 : width 628 height 468 fps 90 pixel format 1
4 : width 628 height 468 fps 60 pixel format 1
5 : width 628 height 468 fps 30 pixel format 1
6 : width 628 height 468 fps 90 pixel format 4
7 : width 628 height 468 fps 60 pixel format 4
8 : width 628 height 468 fps 30 pixel format 4
9 : width 628 height 468 fps 90 pixel format 5
10 : width 628 height 468 fps 60 pixel format 5
11 : width 628 height 468 fps 30 pixel format 5
12 : width 628 height 468 fps 90 pixel format 6
13 : width 628 height 468 fps 60 pixel format 6
14 : width 628 height 468 fps 30 pixel format 6
15 : width 628 height 468 fps 90 pixel format 7
16 : width 628 height 468 fps 60 pixel format 7
17 : width 628 height 468 fps 30 pixel format 7
18 : width 628 height 468 fps 30 pixel format 7
19 : width 628 height 468 fps 30 pixel format 7
20 : width 628 height 468 fps 30 pixel format 7
21 : width 628 height 468 fps 30 pixel format 7
22 : width 628 height 468 fps 30 pixel format 7
23 : width 628 height 468 fps 30 pixel format 7
24 : width 628 height 468 fps 30 pixel format 7
25 : width 628 height 468 fps 30 pixel format 7
26 : width 628 height 468 fps 30 pixel format 7
27 : width 628 height 468 fps 30 pixel format 7
28 : width 628 height 468 fps 30 pixel format 7
29 : width 628 height 468 fps 30 pixel format 7
30 : width 628 height 468 fps 30 pixel format 7
31 : width 628 height 468 fps 30 pixel format 7
32 : width 628 height 468 fps 30 pixel format 7
33 : width 628 height 468 fps 30 pixel format 7
34 : width 628 height 468 fps 30 pixel format 7
35 : width 628 height 468 fps 30 pixel format 7
36 : width 628 height 468 fps 30 pixel format 7
37 : width 628 height 468 fps 30 pixel format 7
38 : width 628 height 468 fps 30 pixel format 7
39 : width 628 height 468 fps 30 pixel format 7
40 : width 628 height 468 fps 30 pixel format 7
41 : width 628 height 468 fps 30 pixel format 7
42 : width 628 height 468 fps 30 pixel format 7
43 : width 628 height 468 fps 30 pixel format 7
44 : width 628 height 468 fps 30 pixel format 7
45 : width 628 height 468 fps 30 pixel format 7
46 : width 628 height 468 fps 30 pixel format 7
47 : width 628 height 468 fps 30 pixel format 7
48 : width 628 height 468 fps 30 pixel format 7
49 : width 628 height 468 fps 30 pixel format 7
50 : width 628 height 468 fps 30 pixel format 7
51 : width 628 height 468 fps 30 pixel format 7
52 : width 628 height 468 fps 30 pixel format 7
53 : width 628 height 468 fps 30 pixel format 7
```

where the pixel formats are the following:

```
enum DSPixelFormat
{
    DS_LUMINANCE8,            ///< Luminance 8 bits
    DS_LUMINANCE16,           ///< Luminance 16 bits
    DS_RGB8,                  ///< Color 8 bits color in order red, green, blue
    DS_BGRA8,                 ///< Color 8 bits color in order blue, green, red, alpha (Equivalent to D3DCOLOR, GL_BGRA)
    DS_NATIVE_L_LUMINANCE8,   ///< Native luminance format, equivalent to DS_LUMINANCE8, for left image only (right image must be disabled)
    DS_NATIVE_L_LUMINANCE16,  ///< Native luminance format, equivalent to DS_LUMINANCE16, for left image only (right image must be disabled)
    DS_NATIVE_RL_LUMINANCE8,  ///< Native pixel-interleaved stereo luminance format, 8 bit pixel from right image, then 8 bit pixel from left image (all 8 bits used)
    DS_NATIVE_RL_LUMINANCE12, ///< Native pixel-interleaved stereo luminance format, 12 bit pixel from right image, then 12 bit pixel from left image (call maxLRBits() to determine how many are used)
    DS_NATIVE_RL_LUMINANCE16, ///< Native pixel-interleaved stereo luminance format, 16 bit pixel from right image, then 16 bit pixel from left image (call maxLRBits() to determine how many are used)
    DS_NATIVE_YUY2,           ///< Native color format, 32 bits per 2x1 pixel patch, with separate 8-bit luminance values (Y), and shared 8-bit chrominance values (U,V) in Y0 U Y1 V order.
    DS_NATIVE_RAW10           ///< Native color format, 40 bits per 4x1 pixel patch, in an 8:8:8:8:2:2:2:2 pattern (10 bits per pixel, high bits first). Bayer patterned: Even rows represent R G R G, odd rows represent G B G B.
};
```

There is no supported color setting. I called the following function sequence

```
        DSAPI * p = DSCreate(DS_DS4_PLATFORM);
    uint32_t serial = DSGetCameraSerialNumber(0);
    if(!p->openDevice())
        std::cout << "device could not be opened" << std::endl;

    if(!p->probeConfiguration())
        std::cout << "probe failed" << std::endl;

    p->enableZ(true);
    p->enableLeft(true);
    p->enableLRCrop(true);

    p->setLoggingLevelAndFile(DS_LOG_ERROR, "log.txt");
    int n = p->getLRZNumberOfResolutionModes(true);
```

Is there anything missing to start the color stream?

Thanks

**Comment by jrgnicho** [comment]
This repo contains an old version of the driver for the Realsense R200.  You might want to take a look at the [new driver](http://wiki.ros.org/RealSense_R200).  I believe it is based on the the driver here but with some improvements and a different API.

**Comment by giacomodabisias** [comment]
Thanks, I got that one but I still got the same issue

**Comment by jrgnicho** [comment]
Judging from a brief look at the _DSSimpleCaptureGL_ sample program it looks like you need to set the resolution mode of the _third_ camera as shown [here](https://github.com/jrgnicho/realsense_drivers/blob/indigo-devel/r200_driver/src/samples/DSSimpleCaptureGL.cpp#L226)

**Comment by giacomodabisias** [comment]
Yeah saw that but the problem is that DS_RGB8 is not supported when asking
for the different formats with
p->getLRZResolutionMode(false, i, w, h, fps, pix);

2016-01-08 16:53 GMT+01:00 Jorge Nicho notifications@github.com:

> Judging from a brief look at the _DSSimpleCaptureGL_ sample program it
> looks like you need to set the resolution mode of the _third_ camera as
> shown here
> https://github.com/jrgnicho/realsense_drivers/blob/indigo-devel/r200_driver/src/samples/DSSimpleCaptureGL.cpp#L226
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jrgnicho/realsense_drivers/issues/1#issuecomment-170037622
> .

## 

Ing G. Dabisias, PhD Student
Percro Lab, (Laboratory of Perceptual Robotics)
Scuola Superiore Sant'Anna
via Luigi Alamanni 13D, San Giuliano Terme 56010 (PI), Italy
mob.: +39 3480839095
skype: giacomo.dabisias2

**Comment by jrgnicho** [comment]
@giacomodabisias 
I think the `getLRZResolutionMode` method only applies to the infrared cameras.  For access to the color one you first have to grab an instance of the [third camera](https://github.com/jrgnicho/realsense_drivers/blob/indigo-devel/r200_driver/src/samples/DSSimpleCaptureGL.cpp#L197) and call `getThirdResolutionMode`.

**Comment by giacomodabisias** [comment]
Thanks, will test that on monday

2016-01-08 20:20 GMT+01:00 Jorge Nicho notifications@github.com:

> @giacomodabisias https://github.com/giacomodabisias
> It looks like you first have to grab an instance of the third camera
> https://github.com/jrgnicho/realsense_drivers/blob/indigo-devel/r200_driver/src/samples/DSSimpleCaptureGL.cpp#L197
> and then call the g_third->setThirdResolutionMode
> https://github.com/jrgnicho/realsense_drivers/blob/indigo-devel/r200_driver/src/samples/DSSimpleCaptureGL.cpp#L226
> method on the third camera instance instead of the getLRZResolutionMode
> method of the _DSAPI_ instance.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jrgnicho/realsense_drivers/issues/1#issuecomment-170098132
> .

## 

Ing G. Dabisias, PhD Student
Percro Lab, (Laboratory of Perceptual Robotics)
Scuola Superiore Sant'Anna
via Luigi Alamanni 13D, San Giuliano Terme 56010 (PI), Italy
mob.: +39 3480839095
skype: giacomo.dabisias2
